import {
  buildTrainingCandidates,
  generateStageRoadmap,
  validateTrainingPlanDraft,
  type GymEquipmentProfile,
  type StageRoadmapGenerationInput,
  type TrainingPlanDraft,
  type ValidatedTrainingPlan,
} from '@fitness-rpg/shared';

/**
 * A fixed UI demo input, not a Stage-planning rule or persisted user profile.
 * The roadmap is always generated by the shared Production Domain below.
 */
export const DEMO_STAGE_ROADMAP_INPUT: StageRoadmapGenerationInput = {
  startDate: '2026-09-22',
  durationDays: 14,
  trainingFrequencyPerWeek: 3,
  mainExerciseId: 'barbell_bench_press',
  stageTargetE1rmKg: 75,
};

export const DEMO_EQUIPMENT_PROFILE: GymEquipmentProfile = {
  id: 'demo-commercial-gym',
  displayName: 'Demo Gym',
  availableEquipmentIds: [
    'barbell',
    'dumbbell',
    'flat_bench',
    'cable_machine',
  ],
};

const demoCandidates = buildTrainingCandidates({
  equipmentProfile: DEMO_EQUIPMENT_PROFILE,
  mainExerciseId: DEMO_STAGE_ROADMAP_INPUT.mainExerciseId,
  targetMuscles: ['chest'],
});

const demoPlanDraft: TrainingPlanDraft = {
  exercises: [
    {
      exerciseId: 'barbell_bench_press',
      role: 'main',
      sets: 3,
      repRange: { min: 8, max: 10 },
    },
    {
      exerciseId: 'dumbbell_bench_press',
      role: 'accessory',
      sets: 3,
      repRange: { min: 8, max: 12 },
    },
    {
      exerciseId: 'cable_chest_fly',
      role: 'accessory',
      sets: 2,
      repRange: { min: 10, max: 15 },
    },
  ],
};

const demoPlanValidation = validateTrainingPlanDraft(demoPlanDraft, demoCandidates);

if (!demoPlanValidation.valid) {
  throw new Error('The fixed demo training plan must satisfy the shared Training Plan validation.');
}

export const DEMO_TRAINING_PLAN: ValidatedTrainingPlan = demoPlanValidation.plan;
export const DEMO_STAGE_ROADMAP = generateStageRoadmap(DEMO_STAGE_ROADMAP_INPUT);
