import type { ExerciseDefinition, ExerciseId } from './exercise.js';

export const EXERCISE_CATALOG = [
  {
    id: 'barbell_bench_press',
    displayName: 'Barbell Bench Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [
      ['barbell', 'flat_bench'],
      ['barbell', 'adjustable_bench'],
    ],
    alternativeExerciseIds: [
      'dumbbell_bench_press',
      'chest_press_machine',
      'push_up',
    ],
  },
  {
    id: 'dumbbell_bench_press',
    displayName: 'Dumbbell Bench Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    requiredEquipmentOptions: [
      ['dumbbell', 'flat_bench'],
      ['dumbbell', 'adjustable_bench'],
    ],
    alternativeExerciseIds: [
      'barbell_bench_press',
      'chest_press_machine',
      'push_up',
    ],
  },
  {
    id: 'incline_dumbbell_press',
    displayName: 'Incline Dumbbell Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [['dumbbell', 'adjustable_bench']],
    alternativeExerciseIds: ['dumbbell_bench_press', 'chest_press_machine'],
  },
  {
    id: 'chest_press_machine',
    displayName: 'Chest Press Machine',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['chest_press_machine']],
    alternativeExerciseIds: [
      'barbell_bench_press',
      'dumbbell_bench_press',
      'push_up',
    ],
  },
  {
    id: 'cable_chest_fly',
    displayName: 'Cable Chest Fly',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    movementPattern: 'chest_fly',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['cable_machine']],
    alternativeExerciseIds: ['dumbbell_chest_fly'],
  },
  {
    id: 'dumbbell_chest_fly',
    displayName: 'Dumbbell Chest Fly',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    movementPattern: 'chest_fly',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [
      ['dumbbell', 'flat_bench'],
      ['dumbbell', 'adjustable_bench'],
    ],
    alternativeExerciseIds: ['cable_chest_fly'],
  },
  {
    id: 'push_up',
    displayName: 'Push-up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    movementPattern: 'horizontal_push',
    difficulty: 'beginner',
    requiredEquipmentOptions: [[]],
    alternativeExerciseIds: [
      'barbell_bench_press',
      'dumbbell_bench_press',
      'chest_press_machine',
    ],
  },
  {
    id: 'barbell_bent_over_row',
    displayName: 'Barbell Bent-over Row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    movementPattern: 'horizontal_pull',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [['barbell']],
    alternativeExerciseIds: ['one_arm_dumbbell_row', 'seated_row_machine'],
  },
  {
    id: 'one_arm_dumbbell_row',
    displayName: 'One-arm Dumbbell Row',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['dumbbell']],
    alternativeExerciseIds: ['barbell_bent_over_row', 'seated_row_machine'],
  },
  {
    id: 'seated_row_machine',
    displayName: 'Seated Row Machine',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    movementPattern: 'horizontal_pull',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['seated_row_machine']],
    alternativeExerciseIds: [
      'barbell_bent_over_row',
      'one_arm_dumbbell_row',
    ],
  },
  {
    id: 'lat_pulldown',
    displayName: 'Lat Pulldown',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'vertical_pull',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['lat_pulldown_machine']],
    alternativeExerciseIds: ['pull_up'],
  },
  {
    id: 'pull_up',
    displayName: 'Pull-up',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    movementPattern: 'vertical_pull',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [['pullup_bar']],
    alternativeExerciseIds: ['lat_pulldown'],
  },
  {
    id: 'barbell_deadlift',
    displayName: 'Barbell Deadlift',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['back', 'quads'],
    movementPattern: 'hinge',
    difficulty: 'advanced',
    requiredEquipmentOptions: [['barbell']],
    alternativeExerciseIds: ['romanian_deadlift'],
  },
  {
    id: 'barbell_overhead_press',
    displayName: 'Barbell Overhead Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    movementPattern: 'vertical_push',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [['barbell']],
    alternativeExerciseIds: [
      'dumbbell_shoulder_press',
      'shoulder_press_machine',
    ],
  },
  {
    id: 'dumbbell_shoulder_press',
    displayName: 'Dumbbell Shoulder Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    movementPattern: 'vertical_push',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['dumbbell']],
    alternativeExerciseIds: [
      'barbell_overhead_press',
      'shoulder_press_machine',
    ],
  },
  {
    id: 'shoulder_press_machine',
    displayName: 'Shoulder Press Machine',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    movementPattern: 'vertical_push',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['shoulder_press_machine']],
    alternativeExerciseIds: [
      'barbell_overhead_press',
      'dumbbell_shoulder_press',
    ],
  },
  {
    id: 'dumbbell_lateral_raise',
    displayName: 'Dumbbell Lateral Raise',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    movementPattern: 'shoulder_abduction',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['dumbbell']],
    alternativeExerciseIds: ['cable_lateral_raise'],
  },
  {
    id: 'cable_lateral_raise',
    displayName: 'Cable Lateral Raise',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    movementPattern: 'shoulder_abduction',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['cable_machine']],
    alternativeExerciseIds: ['dumbbell_lateral_raise'],
  },
  {
    id: 'barbell_curl',
    displayName: 'Barbell Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['barbell']],
    alternativeExerciseIds: ['dumbbell_curl', 'cable_curl'],
  },
  {
    id: 'dumbbell_curl',
    displayName: 'Dumbbell Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['dumbbell']],
    alternativeExerciseIds: ['barbell_curl', 'cable_curl'],
  },
  {
    id: 'cable_curl',
    displayName: 'Cable Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow_flexion',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['cable_machine']],
    alternativeExerciseIds: ['barbell_curl', 'dumbbell_curl'],
  },
  {
    id: 'cable_triceps_pushdown',
    displayName: 'Cable Triceps Pushdown',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['cable_machine']],
    alternativeExerciseIds: ['dumbbell_overhead_triceps_extension'],
  },
  {
    id: 'dumbbell_overhead_triceps_extension',
    displayName: 'Dumbbell Overhead Triceps Extension',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    movementPattern: 'elbow_extension',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['dumbbell']],
    alternativeExerciseIds: ['cable_triceps_pushdown'],
  },
  {
    id: 'close_grip_bench_press',
    displayName: 'Close-grip Bench Press',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    movementPattern: 'horizontal_push',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [
      ['barbell', 'flat_bench'],
      ['barbell', 'adjustable_bench'],
    ],
    alternativeExerciseIds: [],
  },
  {
    id: 'barbell_back_squat',
    displayName: 'Barbell Back Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [
      ['barbell', 'squat_rack'],
      ['barbell', 'power_rack'],
    ],
    alternativeExerciseIds: ['goblet_squat', 'smith_machine_squat', 'leg_press'],
  },
  {
    id: 'goblet_squat',
    displayName: 'Goblet Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['dumbbell']],
    alternativeExerciseIds: [
      'barbell_back_squat',
      'smith_machine_squat',
      'leg_press',
    ],
  },
  {
    id: 'smith_machine_squat',
    displayName: 'Smith Machine Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['smith_machine']],
    alternativeExerciseIds: ['barbell_back_squat', 'goblet_squat', 'leg_press'],
  },
  {
    id: 'leg_press',
    displayName: 'Leg Press',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['leg_press_machine']],
    alternativeExerciseIds: [
      'barbell_back_squat',
      'goblet_squat',
      'smith_machine_squat',
    ],
  },
  {
    id: 'leg_extension',
    displayName: 'Leg Extension',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    movementPattern: 'knee_extension',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['leg_extension_machine']],
    alternativeExerciseIds: [],
  },
  {
    id: 'romanian_deadlift',
    displayName: 'Romanian Deadlift',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [['barbell']],
    alternativeExerciseIds: ['barbell_deadlift'],
  },
  {
    id: 'seated_leg_curl',
    displayName: 'Seated Leg Curl',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    movementPattern: 'knee_flexion',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['leg_curl_machine']],
    alternativeExerciseIds: [],
  },
  {
    id: 'standing_calf_raise',
    displayName: 'Standing Calf Raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    movementPattern: 'calf_raise',
    difficulty: 'beginner',
    requiredEquipmentOptions: [['dumbbell'], ['smith_machine']],
    alternativeExerciseIds: [],
  },
  {
    id: 'barbell_hip_thrust',
    displayName: 'Barbell Hip Thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'hip_extension',
    difficulty: 'intermediate',
    requiredEquipmentOptions: [
      ['barbell', 'flat_bench'],
      ['barbell', 'adjustable_bench'],
    ],
    alternativeExerciseIds: ['glute_bridge'],
  },
  {
    id: 'glute_bridge',
    displayName: 'Glute Bridge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    movementPattern: 'hip_extension',
    difficulty: 'beginner',
    requiredEquipmentOptions: [[]],
    alternativeExerciseIds: ['barbell_hip_thrust'],
  },
] as const satisfies readonly ExerciseDefinition[];

const exerciseById = new Map<ExerciseId, ExerciseDefinition>(
  EXERCISE_CATALOG.map((exercise) => [exercise.id, exercise]),
);

export function getExerciseById(
  exerciseId: ExerciseId,
): ExerciseDefinition | undefined {
  return exerciseById.get(exerciseId);
}
